replicaCount: 1

image:
  repository: nilesh151299/go-web-app
  pullPolicy: IfNotPresent
  tag: "15210794502"


ingress:
  enabled: false
  className: nginx
  annotations:
    # Example annotations (uncomment as needed)
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific